# Build binary
FROM golang:1.14.6 AS builder
#WORKDIR /game
#WORKDIR public_html
WORKDIR /build
WORKDIR /bin

ENTRYPOINT ["start.sh", "elf", "https://kakim:1103558@bitbucket-gsp.com2us.net/scm/cppis/elf.git"]